export const GET_RESOURCES_COUNT = 'GET_RESOURCES_COUNT';
export const GET_RESOURCES_COUNT_FAILED = 'GET_RESOURCES_COUNT_FAILED';
export const START_GETTING_RESOURCES_COUNT = 'START_GETTING_RESOURCES_COUNT';
export const SAVE_USER = 'SAVE_USER';
export const GET_CLUSTERS = 'GET_CLUSTERS';
export const GET_CLUSTERS_FAIL = 'GET_CLUSTERS_FAIL';
export const START_GETTING_CLUSTERS = 'START_GETTING_CLUSTERS';
