// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// METRICS
/* All Admin Metrics
    i.e Workloads, Services, Persistent Volumes and Config stuff
*/

// DEPLOYMENTS
export const FETCH_DEPLOYMENTS = 'FETCH_DEPLOYMENTS';

// JOBS
export const FETCH_JOBS_FAILED = 'FETCH_JOBS_FAILED';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';

// PODS
export const FETCH_PODS_RUNNING = 'FETCH_PODS_RUNNING';
export const FETCH_PODS_PENDING = 'FETCH_PODS_PENDING';
export const FETCH_PODS_SUCCESS = 'FETCH_PODS_SUCCESS';
export const FETCH_PODS_FAILED = 'FETCH_PODS_FAILED';

// NODES
export const FETCH_NODES_TABLE = 'FETCH_NODES_TABLE';
export const FETCH_TOTAL_NODES = 'FETCH_TOTAL_NODES';
export const FETCH_NODES_OUTOFDISK = 'FETCH_NODES_OUTOFDISK';
export const FETCH_NODES_UNAVAILABLE = 'FETCH_NODES_UNAVAILABLE';

