apiVersion: apps/v1
kind: Deployment
metadata:
  name: cranecloud-frontend
  namespace: cranecloud-microservice
  labels:
    app: cranecloud-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cranecloud-frontend
  template:
    metadata:
      labels:
        app: cranecloud-frontend
    spec:
      containers:
        - name: cranecloud-frontend
          image: cranecloud/frontend:latest 
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cranecloud-frontend
  namespace: cranecloud-microservice
spec:
  selector:
    app: cranecloud-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
