apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cranecloud-prod
  labels:
    app: frontend
spec:
  replicas: 1
  minReadySeconds: 15
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cranecloud/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cranecloud-prod
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: frontend
  selector:
    app: frontend
