name: Develop deployment

on:
  push:
    branches:
      - develop
      - ft-add-features

jobs:
  build_and_deploy_staging:
    outputs:
      image: ${{ steps.export.outputs.image }}
      tag: ${{ steps.export.outputs.tag }}

    runs-on: ubuntu-latest
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: true
      cluster: staging-cluster
      VITE_APP_API_BASE_URL: https://staging-api.cranecloud.io
      namespace: cranecloud
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Install (Buildx)
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx version  # Print information to verify that Buildx is set up
        if: runner.os == 'Linux' # Only run on Linux runners

      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Login (GCP)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}

      - name: Get Kubernetes credentials
        run: |
          gcloud container clusters get-credentials $cluster --zone us-central1-a

      - name: Install (Gcloud)
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: Login (GCR)
        # run: gcloud auth configure-docker
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io


      - id: meta
        name: Tag
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Add Env vars
        env:
          VITE_APP_MIRA_API_URL: ${{ secrets.REACT_APP_MIRA_API_URL }}
          VITE_APP_FLUTTERWAVE_PUBLIC_KEY_TESTING: ${{ secrets.REACT_APP_FLUTTERWAVE_PUBLIC_KEY_TESTING }}
          VITE_APP_GITHUB_CLEINT_ID: ${{ secrets.REACT_APP_GITHUB_CLEINT_ID_STAGING }}
          VITE_APP_EXCHANGE_RATE_KEY: ${{ secrets.REACT_APP_EXCHANGE_RATE_KEY }}
          VITE_APP_DOCS_URL: ${{ secrets.REACT_APP_DOCS_URL_STAGING }}
          VITE_APP_DOCKER_EMAIL: ${{ secrets.REACT_APP_DOCKER_EMAIL }}
          VITE_APP_DOCKER_PASSWORD: ${{ secrets.REACT_APP_DOCKER_PASSWORD }}
          VITE_APP_MONITORING_APP: ${{ secrets.REACT_APP_MONITORING_APP_STAGING }}
          VITE_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_STAGING }}
          VITE_APP_ACTIVITY_LOGS_API_URL: ${{ secrets.REACT_APP_ACTIVITY_LOGS_API_URL_STAGING }}
          VITE_APP_MONITORING_API_URL: ${{ secrets.REACT_APP_MONITORING_API_URL_STAGING }}
          VITE_APP_DATABASE_API_URL: ${{ secrets.REACT_APP_DATABASE_API_URL_STAGING }}
          VITE_APP_MLOPS_API_URL: ${{ secrets.REACT_APP_MLOPS_API_URL_STAGING }}
        run: |
          chmod +x ./.github/workflows/bin/create_envs.sh
          ./.github/workflows/bin/create_envs.sh

      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: docker/prod/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - id: export
        name: Export
        uses: actions/github-script@v5
        with:
          script: |
            const metadata = JSON.parse(`${{ steps.meta.outputs.json }}`)
            const fullUrl = metadata.tags.find((t) => t.includes(':sha-'))
            if (fullUrl == null) {
              core.error('Unable to find sha tag of image')
            } else {
              const tag = fullUrl.split(':')[1]
              core.setOutput('image', fullUrl)
              core.setOutput('tag', tag)
            }

      - name: Update deployment image
        run: |
          kubectl set image deployment/frontend frontend=gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:${{ steps.export.outputs.tag }} --record -n $namespace
