name: Test

on:
  push:
  pull_request:

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Dependencies
        run: yarn

      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run Test and Coverage
        run: yarn test --detectOpenHandles --coverage --coverageReporters=lcov
        
      # TODO add coverage report to code climate