name: Test

on:
  push:
  pull_request:

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Dependencies
        run: yarn

      - name: Run Test
        run: yarn test
